FROM ubuntu:14.04

RUN apt-get update
RUN apt-get install -y tar xz-utils wget libpq-dev

ENV POSTGREST_VERSION 0.3.2.0
ENV DB_HOSTNAME db
ENV POSTGREST_DBPORT 5432
ENV POSTGRES_DB postgres
ENV POSTGRES_USER tuna_processor
ENV POSTGRES_PASSWORD postgres
ENV TALLYO_TIMEZONE UTC

RUN wget http://github.com/begriffs/postgrest/releases/download/v${POSTGREST_VERSION}/postgrest-${POSTGREST_VERSION}-ubuntu.tar.xz
RUN tar --xz -xvf postgrest-${POSTGREST_VERSION}-ubuntu.tar.xz
RUN rm postgrest-${POSTGREST_VERSION}-ubuntu.tar.xz
RUN mv postgrest /usr/local/bin/postgrest

COPY docker-entrypoint.sh /
COPY wait-for-it.sh /
RUN chmod +x /docker-entrypoint.sh /wait-for-it.sh

ENTRYPOINT ["/docker-entrypoint.sh"]

EXPOSE 3000

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
