ALTER TABLE box DROP CONSTRAINT boxwp;
ALTER TABLE box DROP CONSTRAINT boxpp;
ALTER TABLE loin DROP CONSTRAINT loinwp;
ALTER TABLE scan DROP CONSTRAINT scanw1p;
ALTER TABLE scan DROP CONSTRAINT scanw2p;
ALTER TABLE scan DROP CONSTRAINT scanpp;
